#!/usr/bin/env python3
"""gen_names.py - regenerate the C++ name table from the TSV data files.

The packet id -> name map lives in two editable text files:

    tools/data/ids_recv.tsv   id <TAB> CMsg<class>     (470 ids, from Ghidra)
    tools/data/overrides.tsv  id <TAB> dir <TAB> name <TAB> meaning

This script merges them and writes the header used by the in-game overlay:

    ConquerDX9Hook/src/hooks/packet_names.h

Each row carries everything the overlay needs to filter on:
  id, the short display name, the CMsg class (from ids_recv.tsv), the
  direction (S/R/B from overrides.tsv) and the one-line meaning.

Run it after editing either TSV. The Python decoder (packet_log.py) reads the
same TSVs directly, so the two stay in sync.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "data")
OUT = os.path.join(HERE, "..", "ConquerDX9Hook", "src", "hooks", "packet_names.h")

# overrides.tsv direction letters -> the enum the C++ side uses.
DIRECTION_CODES = {"S": "PacketDirection::Send", "R": "PacketDirection::Recv",
                   "B": "PacketDirection::Both"}


def load():
    """id -> dict(name, cls, direction, meaning)."""
    cat = {}
    with open(os.path.join(DATA, "ids_recv.tsv"), encoding="utf-8", errors="replace") as f:
        for line in f:
            p = line.rstrip("\n").split("\t")
            if len(p) < 2 or not p[0].startswith("0x"):
                continue
            cls = p[1].strip()
            name = cls[4:] if cls.startswith("CMsg") else cls
            cat[int(p[0], 16)] = {"name": name, "cls": cls,
                                  "direction": "", "meaning": ""}
    with open(os.path.join(DATA, "overrides.tsv"), encoding="utf-8", errors="replace") as f:
        for line in f:
            if not line.strip() or line.lstrip().startswith("#"):
                continue
            p = line.rstrip("\n").split("\t")
            if len(p) < 3 or not p[0].startswith("0x") or "_" in p[0]:
                continue
            try:
                mid = int(p[0], 16)
            except ValueError:
                continue
            name = p[2].strip()
            direction = p[1].strip() if len(p) > 1 else ""
            meaning = p[3].strip() if len(p) > 3 else ""
            entry = cat.setdefault(mid, {"name": "", "cls": "",
                                         "direction": "", "meaning": ""})
            if name:
                entry["name"] = name
            if direction:
                entry["direction"] = direction
            if meaning:
                entry["meaning"] = meaning
    return cat


def c_escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main():
    cat = load()
    rows = sorted((m, e) for m, e in cat.items() if e["name"] and e["name"] != "Unknown")
    out = [
        "// AUTO-GENERATED by tools/gen_names.py from tools/data/*.tsv.",
        "// Do not edit by hand - edit the TSVs and re-run the generator.",
        "#pragma once",
        "#include <cstdint>",
        "",
        "namespace PacketNames {",
        "",
        "\t// Direction the message travels, as recorded in overrides.tsv.",
        "\t//   Send  client -> server only",
        "\t//   Recv  server -> client only",
        "\t//   Both  seen travelling each way",
        "\t//   Any   unknown / never observed",
        "\tenum class PacketDirection : uint8_t { Any = 0, Send = 1, Recv = 2, Both = 3 };",
        "",
        "\tstruct Info",
        "\t{",
        "\t\tuint16_t        id;         // wire msg_id (packet[2..3])",
        "\t\tconst char*     name;       // short display name",
        "\t\tconst char*     className;  // CMsg<...>, \"\" when not recovered",
        "\t\tPacketDirection direction;  // as recorded in the TSV",
        "\t\tconst char*     meaning;    // one-line description, \"\" when unknown",
        "\t};",
        "",
        "\t// Sorted by id; looked up with a binary search.",
        "\tstatic const Info kInfo[] = {",
    ]
    for m, e in rows:
        out.append('\t\t{ 0x%04X, "%s", "%s", %s, "%s" },'
                   % (m, c_escape(e["name"]), c_escape(e["cls"]),
                      DIRECTION_CODES.get(e["direction"], "PacketDirection::Any"),
                      c_escape(e["meaning"])))
    out += [
        "\t};",
        "",
        "\tstatic const int kInfoCount = sizeof(kInfo) / sizeof(kInfo[0]);",
        "",
        "\t// Returns the full record for a message id, or nullptr if not mapped.",
        "\tinline const Info* Find(uint16_t id)",
        "\t{",
        "\t\tint lo = 0, hi = kInfoCount - 1;",
        "\t\twhile (lo <= hi)",
        "\t\t{",
        "\t\t\tint mid = (lo + hi) >> 1;",
        "\t\t\tif (kInfo[mid].id == id) return &kInfo[mid];",
        "\t\t\tif (kInfo[mid].id < id) lo = mid + 1; else hi = mid - 1;",
        "\t\t}",
        "\t\treturn nullptr;",
        "\t}",
        "",
        "\t// Returns a short label for a message id, or \"unknown\" if not mapped.",
        "\tinline const char* Lookup(uint16_t id)",
        "\t{",
        "\t\tconst Info* info = Find(id);",
        '\t\treturn info ? info->name : "unknown";',
        "\t}",
        "",
        "\t// The CMsg class name for an id, or \"\" if not recovered.",
        "\tinline const char* ClassName(uint16_t id)",
        "\t{",
        "\t\tconst Info* info = Find(id);",
        '\t\treturn info ? info->className : "";',
        "\t}",
        "",
        "\t// The recorded direction for an id (PacketDirection::Any if unknown).",
        "\tinline PacketDirection Direction(uint16_t id)",
        "\t{",
        "\t\tconst Info* info = Find(id);",
        "\t\treturn info ? info->direction : PacketDirection::Any;",
        "\t}",
        "",
        "\t// The one-line meaning for an id, or \"\" if not annotated.",
        "\tinline const char* Meaning(uint16_t id)",
        "\t{",
        "\t\tconst Info* info = Find(id);",
        '\t\treturn info ? info->meaning : "";',
        "\t}",
        "",
        "} // namespace PacketNames",
        "",
    ]
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    print("wrote %s (%d ids)" % (os.path.normpath(OUT), len(rows)))


if __name__ == "__main__":
    main()
