#!/usr/bin/env python3
"""gen_names.py - regenerate the C++ name table from the TSV data files.

The packet id -> name map lives in two editable text files:

    tools/data/ids_recv.tsv   id <TAB> CMsg<class>     (470 ids, from Ghidra)
    tools/data/overrides.tsv  id <TAB> dir <TAB> name <TAB> meaning

This script merges them and writes the header used by the in-game overlay:

    ConquerDX9Hook/src/hooks/packet_names.h

Run it after editing either TSV. The Python decoder (packet_log.py) reads the
same TSVs directly, so the two stay in sync.
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "data")
OUT = os.path.join(HERE, "..", "ConquerDX9Hook", "src", "hooks", "packet_names.h")


def load():
    cat = {}
    with open(os.path.join(DATA, "ids_recv.tsv"), encoding="utf-8", errors="replace") as f:
        for line in f:
            p = line.rstrip("\n").split("\t")
            if len(p) < 2 or not p[0].startswith("0x"):
                continue
            name = p[1].strip()
            if name.startswith("CMsg"):
                name = name[4:]
            cat[int(p[0], 16)] = name
    with open(os.path.join(DATA, "overrides.tsv"), encoding="utf-8", errors="replace") as f:
        for line in f:
            if not line.strip() or line.lstrip().startswith("#"):
                continue
            p = line.rstrip("\n").split("\t")
            if len(p) < 3 or not p[0].startswith("0x") or "_" in p[0]:
                continue
            try:
                mid = int(p[0], 16)
            except ValueError:
                continue
            name = p[2].strip()
            if name:
                cat[mid] = name
    return cat


def c_escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main():
    cat = load()
    rows = sorted((m, n) for m, n in cat.items() if n and n != "Unknown")
    out = [
        "// AUTO-GENERATED by tools/gen_names.py from tools/data/*.tsv.",
        "// Do not edit by hand - edit the TSVs and re-run the generator.",
        "#pragma once",
        "#include <cstdint>",
        "",
        "namespace PacketNames {",
        "",
        "\tstruct NamedId { uint16_t id; const char* name; };",
        "",
        "\t// Sorted by id; looked up with a binary search.",
        "\tstatic const NamedId kNames[] = {",
    ]
    for m, n in rows:
        out.append('\t\t{ 0x%04X, "%s" },' % (m, c_escape(n)))
    out += [
        "\t};",
        "",
        "\tstatic const int kNameCount = sizeof(kNames) / sizeof(kNames[0]);",
        "",
        "\t// Returns a short label for a message id, or \"unknown\" if not mapped.",
        "\tinline const char* Lookup(uint16_t id)",
        "\t{",
        "\t\tint lo = 0, hi = kNameCount - 1;",
        "\t\twhile (lo <= hi)",
        "\t\t{",
        "\t\t\tint mid = (lo + hi) >> 1;",
        "\t\t\tif (kNames[mid].id == id) return kNames[mid].name;",
        "\t\t\tif (kNames[mid].id < id) lo = mid + 1; else hi = mid - 1;",
        "\t\t}",
        '\t\treturn "unknown";',
        "\t}",
        "",
        "} // namespace PacketNames",
        "",
    ]
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    print("wrote %s (%d ids)" % (os.path.normpath(OUT), len(rows)))


if __name__ == "__main__":
    main()
